Club/urls.py
from django.urls import path
from . import views

app_name = 'Club'

urlpatterns=[
    path('',views.club_home,name='club_home'),
    path('create/',views.club_reg,name='club_reg'),
    path('membership/',views.membership,name='membership'),
    path('<club_name>/',views.club_detail,name='club_detail'),
]

CollegePortal/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/', include('allauth.urls')),
    path('academics/',include('Academics.urls')),
    path('clubs/',include('Club.urls')),
    path('notice/',include('Notice.urls')),
    path('PostsNQueries/',include('PostsNQueries.urls')),
    path('about/',views.about,name='about'),
    path('contact_us/',views.contact_us,name='contact_us'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostsNQueries/urls.py
from django.urls import path
from . import views

app_name = 'PostsNQueries'

urlpatterns=[
    path('',views.PnQ_home,name='PnQ_home'),
    path('create/',views.create_post,name='create_post'),
    path('add_comment/<int:post_serial>/', views.add_comment, name='add_comment')
]

PostsNQueries/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    post_serial=models.AutoField(primary_key=True)
    posted_by=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.TextField(max_length=10000)
    image = models.ImageField(upload_to='images/',null=True,blank=True)
    time = models.DateTimeField(auto_now_add=True, editable=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True, editable=False)

PostsNQueries/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content','image']
        labels = {
            'content' : 'Write your post',
            'image' : 'You can add image in your post'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=['content']

PostsNQueries/views.py
from django.shortcuts import render,redirect
from .forms import PostForm,CommentForm
from .models import Post

def PnQ_home(request):
    list = Post.objects.all()
    return render(request,'PostsNQueries/PnQ_home.html',{'posts':list})
def create_post(request):
    if request.method=="POST":
        form  = PostForm(request.POST,request.FILES)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.posted_by=request.user
            notice.save()
            return redirect('PostsNQueries:PnQ_home')
    else:
        form = PostForm
    return render(request, 'PostsNQueries/create_post.html',{'form':form})


def add_comment(request, post_serial):
    post = Post.objects.get(post_serial=post_serial)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.commented_by = request.user
            comment.save()
    return redirect('PostsNQueries:PnQ_home') 

PostsNQueries/templates/PostsNQueries/PnQ_home.html
{%extends 'base.html'%}

{%block title%}  Posts & Queries {%endblock%}

{%block header%}Posts & Queries{%endblock%}

{%block content%}
    {% if user.teacher or user.student or user.principal%} <h3><a href="{%url 'PostsNQueries:create_post'%}">Create Post</a></h3></b><br><br>
    {%endif%}
    {% if posts %}
        {% for post in posts %}   
            <div class="post">
                <div class="post-header">
                    <h2>{{ post.posted_by }}</h2>
                    <p>{% load tz %}{{ post.time|date:"F d, Y" }} {% load tz %}({{ post.time|time:"g:i:s A" }})</p>
                </div>
                {% if post.posted_by.teacher%}
                <div class="post-content-teacher">
                    <p>{{ post.content }}</p>
                    {%if post.image%} <img src="{{post.image.url}}" alt="image" height='250' width='300'>
                    {%endif%}
                </div>
                {%else%}
                <div class="post-content">
                    <p>{{ post.content }}</p>
                    {%if post.image%} <img src="{{post.image.url}}" alt="image" height='250' width='300'>
                    {%endif%}
                </div>
                {%endif%}
                <div class="comments">
                    <br><h3><i>Comments</i></h3>
                    {% for comment in post.comments.all%}
                
                    <br><u>{% load tz %}{{ comment.time|time:"g:i A" }}</u> <strong>   {{ comment.commented_by }}:</strong> {{ comment.content }}
                        
                        {% endfor %}
                </div>
                {%if user.is_authenticated%}
                <div class="add-comment">
                    <form method="POST" action="{% url 'PostsNQueries:add_comment' post_serial=post.post_serial %}">
                        {% csrf_token %}
                        <textarea name="content" id="comment_content" required></textarea><br>
                        <button type="submit">Comment</button>
                    </form>
                </div>
                {%else%} <strong>Login or Signup to comment</strong>
                {%endif%}
            </div>            
        {% endfor %}
    {% else %}
        <p>No posts available.</p>
    {% endif %}
{%endblock%}

PostsNQueries/templates/PostsNQueries/create_post.html
{%extends 'base.html'%}

{%block title%}  Create Post {%endblock%}

{%block header%}Posts & Queries{%endblock%}

{%block content%}
 {%if user.is_authenticated%}
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <br>
        <input type="submit" value=" Post ">
    </form>
{%else%} Please Log In or Sign Up to make a post.
{%endif%}
{%endblock%}