Club/urls.py
from django.urls import path
from . import views

app_name = 'Club'

urlpatterns=[
    path('',views.club_home,name='club_home'),
    path('create/',views.club_reg,name='club_reg'),
    path('membership/',views.membership,name='membership'),
    path('<club_name>/',views.club_detail,name='club_detail'),
]

CollegePortal/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/', include('allauth.urls')),
    path('academics/',include('Academics.urls')),
    path('clubs/',include('Club.urls')),
    path('notice/',include('Notice.urls')),
    path('PostsNQueries/',include('PostsNQueries.urls')),
    path('about/',views.about,name='about'),
    path('contact_us/',views.contact_us,name='contact_us'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Club/models.py
from django.db import models
from datetime import date
from django.core.exceptions import ValidationError

def date_validator(x):
    if x>date.today():
        raise ValidationError("Date can not be in the future.")
    

class Club(models.Model):
    club_name = models.CharField(max_length=100, primary_key=True)
    established=models.DateField(validators=[date_validator])
    supervisor = models.ForeignKey('Academics.Teacher', on_delete=models.CASCADE)

    def __str__(self):
        return self.club_name
    
    def save(self,*args,**kwargs):
        self.club_name=self.club_name.title()
        super().save(self,*args,**kwargs)

class Membership(models.Model):
    POSITION_CHOICES = [
        ('Member', 'Member'),
        ('President', 'President'),
        ('Vice President', 'Vice President'),
        ('Secretary', 'Secretary'),
        ('Treasurer', 'Treasurer'),
    ]

    student = models.ForeignKey('Academics.Student', on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES)

Club/forms.py
from django import forms
from .models import Club,Membership

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields= ['club_name','supervisor','established']
        widgets = {
            'established': forms.DateInput(attrs={'type': 'date'}),
        }

class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields= ['club','position']

Club/views.py
from django.shortcuts import render,redirect
from .forms import ClubForm, MembershipForm
from .models import Club,Membership

from django.contrib import messages
def club_home(request):
    clubs=Club.objects.all()
    return render(request, 'Club/club_home.html',{'clubs':clubs})
def club_reg(request):
    if request.method=="POST":
        form  = ClubForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Club:club_home')
    else:
        form = ClubForm
    return render(request, 'Club/club_reg.html',{'form':form})

def membership(request):
    if request.method=="POST":
        form  = MembershipForm(request.POST)
        if form.is_valid():
            existing_membership = Membership.objects.filter(student=request.user.student, club=form.cleaned_data['club']).exclude(pk=form.instance.pk)
            if existing_membership.exists():
                messages.error(request, 'You are already a member of this club.')
                return redirect("Club:club_home")
            membership = form.save(commit=False)
            membership.student=request.user.student
            membership.save()
            messages.success(request, 'Successfully joined the club!')
            return redirect("Club:club_home")
            #redirect to the deatiled view of registered club
    else:
        form = MembershipForm
    return render(request, 'Club/membership.html',{'form':form})

def club_detail(request,club_name):
    memberships=Membership.objects.filter(club__club_name=club_name)
    club=Club.objects.get(club_name=club_name)
    return render(request, 'Club/club_detail.html',{'memberships':memberships,'club':club})

Club/templates/Club/club_detail.html
{%extends 'base.html'%}

{%block title%}  {{club.club_name}} Club{%endblock%}

{%block header%}{{club.club_name}} Club {%endblock%}
{%block content%}
<div class="lists">
This club was established in : {{club.established}}<br>
<br> The club is supervised by <b style="color:#457802;">{{club.supervisor }} ({{club.supervisor.dept_name}})</b> <br><br>
{%if memberships%}
    {{memberships.count}} Member in this club<br><br>
    {%for membership in memberships%}
        {{membership.student}}-{{membership.position}} <br>
    {%endfor%}
{%else%}<b>No club members in this club yet.</b> 
{%endif%}
</div>
{%endblock%}

Club/templates/Club/club_home.html
{%extends 'base.html'%}

{%block title%}  College Clubs  {%endblock%}

{%block header%}College Clubs{%endblock%}

{%block content%}
    {% if messages %}
        {% for message in messages %}
        <h3 style="color:rgb(248, 221, 180);">{{ message }}</h3>
        {% endfor %}
    {% endif %}
    {% if user.teacher%} <a href="{%url 'Club:club_reg'%}">Create Club</a><br><br><br>
    {%endif%}
    {% if user.student%} <a href="{%url 'Club:membership'%}">Get in a Club!</a><br><br><br>
    {%endif%}
    <div class="lists">
        {%if clubs%}
        We have <i>{{clubs.count}}</i> Clubs! <br>
        <br><b>List of our Clubs:</b><br><br>
        {%for i in clubs%}
           <p><a href="{% url 'Club:club_detail' club_name=i.club_name%}">{{i.club_name}} </a> </p>
        {%endfor%}
        {%else%}<b> No club is created yet</b>
        {%endif%}
    </div> 
{%endblock%}

Club/templates/Club/club_reg.html
{%extends 'base.html'%}

{%block title%}  Create Club {%endblock%}

{%block header%}College Clubs{%endblock%}

{%block content%}
    {%if user.principal or user.teacher%}
    <form method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <br>
        <input type="submit" value=" Create Club ">
    </form>
    {%else%} 
    <p>You are not a teacher</p>
    {%endif%}
{%endblock%}

Club/templates/Club/membership.html
{%extends 'base.html'%}

{%block title%}  Club Membership {%endblock%}

{%block header%}College Clubs{%endblock%}

{%block content%}

    {%if user.student%}
    <form method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <br>
        <input type="submit" value=" Get In! ">
    </form>
    {%else%} 
    <p>Membership is only for students</p>
    {%endif%}

{%endblock%}